[files]
extend-exclude = ["LICENSE", ".gitignore"]

[default.extend-identifiers]
aks = "aks"
AKS = "AKS"

[default.extend-words]
"ba" = "ba"
"center"="center"
"ve"="ve"
"tes"="tes"
"parametrize"="parametrize"

[default]
locale = "en-gb"
