[files]
extend-exclude=["experiments/*.ipynb", ".gitignore", "LICENSE", ".*"]

[default.extend-identifiers]
aks="aks"
AKS="AKS"

[default.extend-words]
"ba"="ba"
"center"="center"
"ve"="ve"
"tes"="tes"
"parametrize"="parametrize"
"dum"="dum"
"te"="te"

[default]
locale="en-gb"
