apiVersion: v1
kind: ConfigMap
metadata:
  name: metric-db-secret-credentials
  labels:
    app: postgresdb
data:
  POSTGRES_DB: postgres
  # Db user
  POSTGRES_USER: postgres
  # Db password
  POSTGRES_PASSWORD: postgres
