apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: chroma-server-index
  name: chroma-server-index
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
