apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: chroma-clickhouse-backups
  name: chroma-clickhouse-backups
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
