steps:
  fetch_data_step:
    enable_cache: False
    parameters:
      data_version: "v1.0"
  embed_data_step:
    enable_cache: True
  upload_data_to_vector_db_step:
    enable_cache: False
    parameters:
      data_version: "v1.0"
