steps:
  load_data:
    enable_cache: False
    parameters:
      data_version: "v1.0"
      data_postfix: "validated"
  embed_data:
    enable_cache: True
  upload_data_to_vector_db:
    enable_cache: False
    parameters:
      data_version: "v1.0"
