steps:
  load_data:
    enable_cache: False
    parameters:
      data_version: "data/first_version"
      data_postfix: "validated"
  embed_data:
    enable_cache: False
    parameters:
      data_version: "data/first_version"
      embed_model_type: "base"
      chunk_size: 1000
      chunk_overlap: 200
