name: CI

on:
  workflow_call:
  pull_request:
    branches:
      - main
      - develop
  push:
    branches:
      - main
      - develop

jobs:
  ci-tests:
    name: Pytest CI
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    timeout-minutes: 15

    # disable zenml analytics logging for ci
    env:
      ZENML_ANALYTICS_OPT_IN: false

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        id: setup-python
        with:
          python-version: ${{ matrix.python-version }}

      # The key configuration value here is `virtualenvs-in-project: true`: this creates the
      # venv as a `.venv` in your testing directory, which allows the next step to easily
      # cache it.
      - uses: snok/install-poetry@v1
        with:
          version: 1.3.1
          virtualenvs-create: true
          virtualenvs-in-project: true
          installer-parallel: true

      - name: Spelling checker
        uses: crate-ci/typos@master
        with:
            files: "."
            config: ./.typos.toml


      # Cache your dependencies (i.e. all the stuff in your `pyproject.toml`).
      - name: Load cached venv
        id: cached-poetry-dependencies
        uses: actions/cache@v3
        with:
          path: .venv
          key: venv-${{ runner.os }}-${{ steps.setup-python.outputs.python-version }}-${{ hashFiles('**/poetry.lock') }}

      # Install dependencies if cache does not exist
      - name: Install dependencies
        if: steps.cached-poetry-dependencies.outputs.cache-hit != 'true'
        run: |
          sed '/zenml/d' pyproject.toml > pyproject2.toml
          mv pyproject2.toml pyproject.toml
          poetry lock
          poetry install

      # Install zenml separately due to pyyaml bug : https://github.com/yaml/pyyaml/issues/724
      - name: Install additional dependencies
        run: |
          source .venv/bin/activate
          pip install "cython<3" wheel && pip install --no-build-isolation "pyyaml==5.4.1"
          pip install "zenml==0.40.3"

      - name: Setup ZenML
        run: |
          source .venv/bin/activate
          zenml integration install huggingface pytorch seldon -y

      - name: Run the full test suite
        run: |
          source .venv/bin/activate
          python -m pytest tests --cov
